apiVersion: ripsaw.cloudbulldozer.io/v1alpha1
kind: Benchmark
metadata:
  name: byowl-benchmark
  namespace: my-ripsaw
spec:
  workload:
    name: byowl
    args:
      image: quay.io/multi-arch/cloud-bulldozer:uperf
      clients: 1
      commands: |
        echo 'Test';
        echo 'Test2'
